[% USE date %]

<?xml version="1.0" encoding="iso-8859-15"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>AWStats MultiSite Summary for "[% username %]"</title>
    <meta http-equiv="Content-Style-Type" content="text/css" />

    <style type="text/css">
      <!--
      body {
         font            : 12px/1.2 Verdana, Arial, Helvetica, Sans-Serif;
         text-align      : center;
      }

      td {
         font            : 12px/1.2 Verdana, Arial, Helvetica, Sans-Serif;
      }

      td.header {
         font            : 12px/1.2 Verdana, Arial, Helvetica, Sans-Serif;
         text-align      : center;
         font-weight     : bold;
      }

      p.disclaimer {
         font            : 10px/1.2 Verdana, Arial, Helvetica, Sans-Serif;
         text-align      : center;
      }

      h1 {
         font            : 14px/1.4 Verdana, Arial, Helvetica, Sans-Serif;
         font-weight     : bold;
         text-align      : center;
      }

      #content {
         width           : 640px;
         margin-right    : auto;
         margin-left     : auto;
         margin-top      : 10px;
         padding         : 0px;
         text-align      : left;
      }
      -->
    </style>
  </head>

  <body>

    <div id="content">
      <h1>AWStats MultiSite Summary<br>for user "[% username %]"</h1>

      <table border="0" cellspacing="4" cellpadding="4">
        <tr>
          <td class="header" width="100" bgcolor="#ECECEC">Statistics for</td>
          <td class="header" width="75" bgcolor="#FFB055">Unique visitors</td>
          <td class="header" width="75" bgcolor="#F8E880">Number of visits</td>
          <td class="header" width="75" bgcolor="#4477DD">Pages</td>
          <td class="header" width="75" bgcolor="#66F0FF">Hits</td>
          <td class="header" width="75" bgcolor="#2EA495">Bandwidth</td>
          <td class="header" width="75" bgcolor="#ECECEC">Last<br>Update<td>
        </tr>
        [%- FOREACH site = sites %]
          <tr>
            <td><a href="[% awstats %]?config=[% site.configname %]" onMouseover="window.status='Statistics for [% site.name %]'; return true;" onMouseout="window.status=''; return true;">[% site.name %]</td>
            <td align="right">[% site.visitors %]</td>
            <td align="right">[% site.visits %]</td>
            <td align="right">[% site.pages %]</td>
            <td align="right">[% site.hits %]</td>
            <td align="right">[% site.bandwidth %] [% site.bandwidth_suffix %]</td>
            <td align="right" nowrap>[% site.lastupdate %]</td>
          </tr>
        [%- END %]
      </table>

      <p>To get a detailed view please click on the corresponding link.</p>
      <p class="disclaimer">This site was generated by <a href="http://www.25th-floor.com/oss" target="_blank">AWStats Multisite Summary</a> [% version %]<br>(c) 2004 by <a href="http://www.25th-floor.com" target="_blank">25th-floor</a> de Pretis & Helmberger KEG</p>
    </div>

  </body>
</html>
